### ISSUE TITLE
遇到“无法加载主类 org.gradle.wrapper.GradleWrapperMain”怎么解决?

### ISSUE THREAD

**Issue by liqy** [mcxiaoke/gradle-packer-plugin#1]
无法加载主类 org.gradle.wrapper.GradleWrapperMain”怎么解决?

**Comment by shen076** [comment]
请问楼主解决问题了么？

**Comment by AlexanderYao** [comment]
copy android/gradle/wrapper/gradle-wrapper.jar to the same location from other projects

**Comment by zhangzzqq** [comment]
如果你用的是androidStudio3.0以上的版本，新建一个android工程的时候在gradle/wrapper里面默认会有一个gradle-wrapper.jar文件，把这个拷贝到你项目中对gradle/wrapper中，就可以了。
