### ISSUE TITLE
Android plugin 1.5+ is not supported.

### ISSUE THREAD

**Issue by qianyiliushang** [mcxiaoke/gradle-packer-plugin#10]
```shell
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/chenpengpeng/android-client/new-trunk/app/build.gradle' line: 67

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'packer']
   > the android plugin 1.5.+ is not supported.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

67行代码为：
```java
apply plugin: 'packer'
```

**Comment by mcxiaoke** [comment]
@qianyiliushang 使用的是最新的1.0.4版吗，如果不是更新一下应该就可以了

**Comment by qianyiliushang** [comment]
@mcxiaoke 不好意思，当时没有成功之后我就换成直接用gradle打包了了，有空再试一下这个插件。

**Comment by xiangxm** [comment]
Failed to apply plugin [id 'packer']
博主，我也遇到了、
Build file 'D:\Work\Projects\FlowerWaiter\app\build.gradle' line: 6

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'packer']
   > :app invalid market file: D:\Work\Projects\FlowerWaiter\markets
使用的是最新版本插件1.0.5
