### ISSUE TITLE
java版本写注释安装失败问题

### ISSUE THREAD

**Issue by songxd** [mcxiaoke/gradle-packer-plugin#11]
{使用Java写入APK文件注释虽然可以正常读取，但是安装的时候会失败，错误信息是：

adb install -r demo.apk
Failure [INSTALL_FAILED_INVALID_APK]
原因未知，可能Java的Zip实现写入了某些特殊字符导致APK文件校验失败，于是只能放弃这个方法。同样的功能使用Python测试完全没有问题，处理后的APK可以正常安装。}

上面的问题可以使用zip4j进行写注释操作，亲测不会出现上述问题
https://github.com/songxd/AndroidMultiChannelBuildTool-Java

**Comment by mcxiaoke** [comment]
@songxd 地址是这里 <https://github.com/mcxiaoke/packer-ng-plugin> Java版和Python版都有

**Comment by songxd** [comment]
Y(^_^)Y
