### ISSUE TITLE
没有生成默认文件名格式的 apk？

### ISSUE THREAD

**Issue by voidhug** [mcxiaoke/gradle-packer-plugin#15]
默认格式是  ${appPkg}-${flavorName}-${buildType}-v${versionName}-${versionCode}，
我指定了版本号为 ./gradlew -PbuildNum=1.0 clean assembleRelease，
但是我生成的是 app-release-unsigned.apk

**Comment by mcxiaoke** [comment]
仔细看文档，文件名格式只适用于渠道打包 
```shell
./gradlew -Pmarket=markets.txt clean archiveApkRelease
```
