### ISSUE TITLE
与Android7.0 的APK Signature Scheme v2 方式冲突

### ISSUE THREAD

**Issue by Rock610** [mcxiaoke/gradle-packer-plugin#17]
Android N引入一项新的应用签名方案 APK Signature Scheme v2,貌似与此方案冲突，安装apk时会提示签名不一致，该应用可能已被恶意篡改.或者有的手机是提示 该软件包似乎已损坏.具体可以看看这个[链接](http://blog.5ibc.net/p/94059.html)

**Comment by mcxiaoke** [comment]
仔细看ReadMe，有说明
