### ISSUE TITLE
抱歉，实在没有翻到相关的内容

### ISSUE THREAD

**Issue by Rock610** [mcxiaoke/gradle-packer-plugin#18]
这个是7.0才加入的 APK Singnature Scheme v2

**Comment by Rock610** [comment]
7.0是今年才发布的，我看你最后一次修改是一年前，不知道如何去兼容APK Singnature Scheme v2?

**Comment by mcxiaoke** [comment]
你走错地方了，看这里： https://github.com/mcxiaoke/packer-ng-plugin
