### ISSUE TITLE
test market and archives apk build. FAILURE:

### ISSUE THREAD

**Issue by xing-kenny** [mcxiaoke/gradle-packer-plugin#2]
test market and archives apk build.
Download https://repo1.maven.org/maven2/com/android/tools/dvlib/24.0.1/dvlib-24.0.1.pom

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'sample'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve com.squareup:javawriter:2.5.0.
     Required by:
         :sample:unspecified > com.android.tools.build:gradle:1.0.1 > com.android.tools.build:builder:1.0.1
      > Could not parse POM https://repo1.maven.org/maven2/com/squareup/javawriter/2.5.0/javawriter-2.5.0.pom
         > Could not download artifact 'oss-parent.pom (org.sonatype.oss:oss-parent:7)'
            > Could not HEAD 'https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/7/oss-parent-7.pom'.
               > Read timed out
      > Could not HEAD 'https://oss.sonatype.org/content/repositories/snapshots/com/squareup/javawriter/2.5.0/javawriter-2.5.0.jar'.
         > Read timed out
   > Could not resolve org.apache.httpcomponents:httpclient:4.1.1.
     Required by:
         :sample:unspecified > com.android.tools.build:gradle:1.0.1 > com.android.tools.build:builder:1.0.1 > com.android.tools:sdklib:24.0.1
      > Could not parse POM https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.1.1/httpclient-4.1.1.pom
         > Could not resolve org.apache.httpcomponents:httpcomponents-client:4.1.1.
            > Could not parse POM https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcomponents-client/4.1.1/httpcomponents-client-4.1.1.pom
               > Could not download artifact 'project.pom (org.apache.httpcomponents:project:4.1.1)'
                  > Could not HEAD 'https://repo1.maven.org/maven2/org/apache/httpcomponents/project/4.1.1/project-4.1.1.pom'.
                     > Read timed out

* Try:
Run with --info or --debug option to get more log output.

**Comment by mcxiaoke** [comment]
你发的错误消息不是已经说明了吗：Could not HEAD 'https://oss.sonatype.org/content/repositories/snapshots/com/squareup/javawriter/2.5.0/javawriter-2.5.0.jar'. 跟packer没关系，检查下你的网络吧
