### ISSUE TITLE
packer用gradle2.2.0 打包失败

### ISSUE THREAD

**Issue by chenxiaokai** [mcxiaoke/gradle-packer-plugin#20]
工程用packer com.mcxiaoke.gradle:packer:1.0.+ 并且 gradle2.2.0 打包的时候，抛出异常“Could not find com.android.tools.build:gradle:2.2.0”

**Comment by mcxiaoke** [comment]
看起来与packer没关系，去掉packer正常打包试试

**Comment by mcxiaoke** [comment]
@chenxiaokai buildscript.repositories 里加入 jcenter()

**Comment by chenxiaokai** [comment]
@mcxiaoke 谢谢 已经解决了
