### ISSUE TITLE
win8下报错

### ISSUE THREAD

**Issue by Juneor** [mcxiaoke/gradle-packer-plugin#6]
Microsoft Windows [版本 6.3.9600]                                                                                                                                                        
(c) 2013 Microsoft Corporation。保留所有权利。                                                                                                                                           

C:\Users\Administrator\Documents\GitHub\xxxxxxx>gradlew -Pmarket=markets.txt clean archiveApkRelease
:actionbarsherlock:clean UP-TO-DATE                                                                                        
:androidcrop:clean UP-TO-DATE     
:app:cleanArchives                
:app:clean FAILED         
             
FAILURE: Build failed with an exception.
             
* What went wrong:
Execution failed for task ':app:clean'.
> Unable to delete file: C:\Users\Administrator\Documents\GitHub\xxxxxxx\app\build\intermediates\exploded-aar\kaozhengbao_androidStudio\actionbarsherlock\unspecified\r
es\drawable-hdpi\abs__ab_solid_dark_holo.9.png
             
* Try:       
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
             
BUILD FAILED 
             
Total time: 2 mins 41.408 secs
             
C:\Users\Administrator\Documents\GitHub\xxxxxxx>M m'M

**Comment by mcxiaoke** [comment]
这个跟gradle-packer-plugin没关系，是Gradle的问题，你重启Android Studio，或者在命令行手动清除build目录即可解决
