### ISSUE TITLE
代码混淆后打包失败了

### ISSUE THREAD

**Issue by fflamingogo** [mcxiaoke/gradle-packer-plugin#7]
release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
本来是可以多渠道打包的，把false改为true，使用混淆打包，然后打包出错了，应该如何解决？

**Comment by mcxiaoke** [comment]
@fflamingogo 看具体的错误信息，修改proguard的配置，这个跟打包工具应该是无关的
