### ISSUE TITLE
packer.archiveNameFormat doesn't work？

### ISSUE THREAD

**Issue by renhuihhh** [mcxiaoke/gradle-packer-plugin#8]
我发现我配好packer的archiveNameFormat但是不起效果

这是我的gradle脚本的头部
apply plugin: 'com.android.application'
apply plugin: 'packer'
def dest='.'

packer {
    // 指定渠道打包输出目录
    //archiveOutput = file(new File(project.rootProject.buildDir.path, "apks"))
    // 指定渠道打包输出文件名格式
    archiveNameFormat = '${appName}_${versionName}_${flavorName}_${buildTime}'
    // 指定渠道打包需要修改的AndroidManifest文件项
    manifestMatcher = ['UMENG_CHANNEL','CHANNEL']
    // 指定是否使用build版本号自增
    //buildNumberAuto = true
    // 指定使用版本号自增的buildType，默认是全部
    //buildNumberTypeMatcher = ['release']

}

这是输出的apk目录
-rw-rw-r-- 1 renhui renhui 17882958 12月  7 16:52 Uplus-shuomingshu-release.apk
-rw-rw-r-- 1 renhui renhui 17881193 12月  7 16:52 Uplus-shuomingshu-release-unaligned.apk
-rw-rw-r-- 1 renhui renhui 17882967 12月  7 16:53 Uplus-xmedia-release.apk
-rw-rw-r-- 1 renhui renhui 17881204 12月  7 16:53 Uplus-xmedia-release-unaligned.apk

这文件名到底谁控制的？

**Comment by mcxiaoke** [comment]
这里的文件名模板个事只应用于渠道打包任务(archiveApkRelease等)，对普通的 ./gradlew assembleRelease assembleDebug不生效

**Comment by mcxiaoke** [comment]
```groovy
archiveNameFormat = 'myapp-${appPkg}-${flavorName}-${buildType}-v${versionName}'
```

```shell
 ./gradlew -Pmarket=markets.txt clean archiveApkRelease
```

```shell
myapp-com.mcxiaoke.next-Google_Play-release-v1.0.0.apk
myapp-com.mcxiaoke.next-Gradle_Test-release-v1.0.0.apk
myapp-com.mcxiaoke.next-SomeMarket-release-v1.0.0.apk
```

我测试没问题
